#!/bin/sh

# Author : Stanley <git.io/monesonn>

# Script version
__version="0.1.0-rc1"

# Some variables to initialize colors for colorfull echo output
BLUE='\033[1;34m'
RED='\033[31m'
CYAN='\033[1;36m'
NC='\033[0m'

# Variables

DIR=''
PLAYLIST_DIR='$HOME/Music/playlists/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s'

_help() {
cat << EOF

 ▀▄▀ ▄▀▄ ▀█▀ ▄▀▄  
  █  █▀█  █  █▀█.sh                
EOF
echo -e "${BLUE} Ultimate audio download script${NC}"

cat << EOF

 Description: CLI-wrapper for youtube-dl written on Shell

 Usage: $(basename $0) [OPTION] URL [URL...]

 Options:                       
  -h | --help | help            Show this message
  -v | --version | version      Show script version
  -p | --playlist | playlist    Download playlist ... 

 Example: yata -p url
EOF
}

err_msg() { echo -e "${RED}$1${NC}"; }

__main__() {
  case $# in
  0) _help ; exit 1 ;;
  1) case $1 in
      -h | --help | help) _help ;;
      -v | --version | version) printf "$__version\n" ;;
      # -p | --playlist | playlist)  ;;
      *) err_msg "No such option: $1" ; exit 1 ;;
    esac;;
  2) 
    if [[ "$1" == "-p" || "$1" == "--playlist" || "$1" == "playlist" ]]; then
      youtube-dl --embed-thumbnail --ignore-errors --extract-audio --audio-format mp3 --output "$PLAYLIST_DIR" "$2"
    else err_msg "Input error." ; exit 1
    fi;;  
  *) err_msg "Input error, too many arguments.\nType yata [-h|--help|help] to see a list of all options." ; exit 1 ;;
  esac
}

__main__ "$@"
